# Generated by Django 2.2.28 on 2024-03-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image_path',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture_path',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='foodieshare/images/user.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='foodieshare/images/meal.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='nutrition',
            field=models.TextField(),
        ),
    ]
