# Generated by Django 2.2.28 on 2024-03-17 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieshare', '0004_auto_20240314_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='foodieshare/images/meal.jpg', upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
