# Generated by Django 2.2.28 on 2024-03-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieshare', '0005_auto_20240317_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='static/foodieshare/images/meal.jpg', upload_to='post_images/'),
        ),
    ]
