# Generated by Django 2.2.28 on 2024-03-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieshare', '0007_auto_20240317_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='defaults/meal.jpg', upload_to='post_images/'),
        ),
    ]
