# Generated by Django 2.2.28 on 2024-03-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieshare', '0008_auto_20240317_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='example.jpg', upload_to='post_images/'),
        ),
    ]
