# Generated by Django 2.2.28 on 2024-03-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieshare', '0010_auto_20240317_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='user.jpg', upload_to='profile_pics/'),
        ),
    ]
