# Generated by Django 2.2.28 on 2024-03-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodieshare', '0012_auto_20240320_1211'),
        ('foodieshare', '0011_auto_20240320_1222'),
    ]

    operations = [
    ]
