# Generated by Django 2.2.28 on 2024-03-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodieshare', '0013_merge_20240320_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nutrition',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=255),
        ),
    ]
